const seasonLines = [
  "Let's Explore In ",
  "Experience The Thrill In ",
  "Immerse Yourself In ",
  "Refresh Yourself In ",
  "Embrace Nature In ",
  "Discover The Magic In ",
  "Find Peace In ",
  "Unleash The Fun In ",
  "Get Ready For ",
  "Step Into The ",
  "Chase The Sun In ",
  "Bask In The Glory Of ",
  "Feel The Rush In ",
  "Live Life To The Fullest In ",
  "Connect With Nature In ",
];

const stateLines = [
  "Embark A Memorable Trek ",
  "Journey Through Diverse Terrains Of ",
  "Explore The Hidden Treasures Of ",
  "Shall We Discover ",
  "Create Memories In ",
  "Do Some Adventure In ",
  "This Is Time For ",
  "Wander Through ",
  "Unveil The Secrets Of ",
  "Get Lost In The Beauty Of ",
  "Find Solace In ",
  "Discover New Horizons In ",
  "Breathe Fresh Air In ",
  "Challenge Yourself In ",
  "Push Your Limits In ",
  "Step Out Of Your Comfort Zone In ",
  "Explore The Unknown In ",
  "Create Your Own Path In ",
  "Live The Adventure In ",
  "Journey Of A Lifetime In ",
  "Make Memories That Last ",
];

const difficultyLines = [
  "Unleash Your Adventurous Spirit With ",
  "Get Ready For A ",
  "Step Out Of Your Comfort Zone With ",
  "Challenge Yourself With ",
  "Push Your Limits With ",
  "Test Your Endurance With ",
  "Conquer The Trails With ",
  "Elevate Your Hiking Game With ",
  "Take On The Challenge With ",
  "Face Your Fears With ",
  "Discover Your Strength With ",
  "Go Beyond Your Limits With ",
  "Experience The Rush With ",
  "Prove Yourself With ",
  "Reach New Heights With ",
];

export { seasonLines, stateLines, difficultyLines };
